/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  english: [{
		  type: 'autogenerated',
		  dirName: 'english',
		},
	],
	linux1: [{
		  type: 'autogenerated',
		  dirName: 'linux',
		},
	],
	mysql: [{
	  type: 'autogenerated',
	  dirName: 'mysql',
	}],nginx: [{
	  type: 'autogenerated',
	  dirName: 'nginx',
	}],
	python: [{
		type: 'autogenerated',
		dirName: 'python',
	}],
};

module.exports = sidebars;
